<?php 

/**
 * @author Kashyap Team
 * @copyright Copyright (c) 2018 Kashyap (http://kashyapsoftware.com/)
 * @package Kashyap_Customcollection
*/

$product_count     = $this->getData('product_count');
$_customCollection = $block->getMostViewCollection($product_count);
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_listBlock = $block->getListBlock();
$pos = $_listBlock->getPositioned();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
$attribute_code = "most_view";
?>
<div class="custom_collection">
	<div class="page-title"><h3><?= $this->getData('title') ?></h3></div>
	<?php 
		if(($_customCollection == false) ||(count($_customCollection)<=0))
		{ 
	?>
		<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
	<?php
		}
		else
		{
	?>
		<div class="products wrapper grid products-grid">
	        <ul id="owlslider-<?= $attribute_code ?>" class="products list items product-items products list items product-items owlslider">
				<?php foreach ($_customCollection as $_product) : ?>
					<?php //print_r($_product->getData()); ?>
					<li class="item product product-item">
						<div class="product-item-info" data-container="product-grid">
		                    <?php
			                    $productImage = $_listBlock->getImage($_product, 'category_page_grid');
			                    if ($pos != null) {
			                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
			                            . 'top:' . $productImage->getHeight() . 'px;"';
			                    }
			                ?>
		                    <?php // Product Image ?>
		                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
		                        <?= $productImage->toHtml() ?>
		                    </a>

		                    <div class="product details product-item-details">
		                        <?php
		                            $_productNameStripped = $_listBlock->stripTags($_product->getName(), null, true);
		                        ?>
		                        <strong class="product name product-item-name">
		                            <a class="product-item-link"
		                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
		                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
		                            </a>
		                        </strong>
		                        <?= $_listBlock->getReviewsSummaryHtml($_product, $templateType) ?>
		                        <?= /* @escapeNotVerified */ $_listBlock->getProductPrice($_product) ?>
		                        <?= $_listBlock->getProductDetailsHtml($_product) ?>

		                        <div class="product-item-inner">
		                            <div class="product actions product-item-actions"<?= strpos($pos, 'grid' . '-actions') ? $position : '' ?>>
		                                <div class="actions-primary"<?= strpos($pos, 'grid' . '-primary') ? $position : '' ?>>
		                                    <?php if ($_product->isSaleable()): ?>
		                                        <?php $postParams = $_listBlock->getAddToCartPostParams($_product); ?>
		                                        <form data-role="tocart-form" data-product-sku="<?= $_listBlock->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
		                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
		                                            <input type="hidden" name="uenc" value="<?= /* @escapeNotVerified */ $postParams['data']['uenc'] ?>">
		                                            <?= $_listBlock->getBlockHtml('formkey') ?>
		                                            <button type="submit"
		                                                    title="<?= $_listBlock->escapeHtml(__('Add to Cart')) ?>"
		                                                    class="action tocart primary">
		                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
		                                            </button>
		                                        </form>
		                                    <?php else: ?>
		                                        <?php if ($_product->isAvailable()): ?>
		                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
		                                        <?php else: ?>
		                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
		                                        <?php endif; ?>
		                                    <?php endif; ?>
		                                </div>
		                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, 'grid' . '-secondary') ? $position : '' ?>>
		                                    <?php if ($addToBlock = $_listBlock->getChildBlock('addto')): ?>
		                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
		                                    <?php endif; ?>
		                                </div>
		                            </div>
		                        </div>
		                    </div>

						</div>
					</li>
				<?php endforeach; ?>
	        </ul>
	    </div>
	    <?php if (!$_listBlock->isRedirectToCartEnabled()) : ?>
		    <script type="text/x-magento-init">
		    {
		        "[data-role=tocart-form], .form.map.checkout": {
		            "catalogAddToCart": {
		                "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
		            }
		        }
		    }
		    </script>
		<?php endif; ?>
    		<script>
		        require(['jquery', 'ks_owlcarousel'], function ($) {
	                $(document).ready(function(){	                   
						$("#owlslider-<?= $attribute_code ?>").owlCarousel({
		                    items:5,
						    loop:true,
						    margin:10,
						    nav:true,
						    pagination : true,
						    responsive:{
						        0:{
						            items:1
						        },
						        600:{
						            items:3
						        },
						        1000:{
						            items:5
						        }
						    }
			            });
	                });
	            });
		    </script>

	<?php
		}
	?>
</div>